### PR TITLE
#4: Force the predictions drawer position update

### LINKED ISSUE #4: weird positioning issue
the location of the suggested results displays very far from the input field. I'm using bootstrap to style my form, and nothing else. 
screen shot 2014-11-11 at 12 59 47 pm

### PR DESCRIPTION
**Pull request by alexfdz**
fixes #4

### CODE REVIEW

**Comment by kuhnza** [comment]
Thanks @alexfdz I'm not getting much time to maintain this right now so I've made you a contributor.

**Comment by alexfdz** [comment]
thanks @kuhnza, who should validate the pull then, anyother contributor?

**Comment by rallin** [comment]
@alexfdz, I think it would be better if someone one will continue to maintain yourself the project. Then he will validate pull requests. Do you want to become maintainer?

**Comment by kuhnza** [comment]
Happy for someone to put their hand up. I'll contribute where/when I get time.

**Comment by alexfdz** [comment]
@rallin @kuhnza Happy to became maintainer! but as per my limited angularjs experience, I still think that someone else should review and merge the pull request.

**Pull request merged**
