### PR TITLE
Update - Add geolocation service

### PR DESCRIPTION
**Pull request by fcailliez**
Hello,

If you add `data-geolocation="true" ` in the input field, now, you can get the current postion of the device.
Browser compatibility : chrome, firefox, ie 9, opera, safari
> https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

Tested!

### CODE REVIEW

**Comment by simonferndriger** [comment]
Hi

Thank you very much, this is awesome! Do you perhaps also have a quick example of how to add an icon in Angular which fills the input field with the current position?

**Comment by fcailliez** [comment]
You can add a class on the input field. It's very simple.

Steps: 
1- You add a new class on the CSS file :
```
.input-geolocation {
    background: url(/asset/google/geolocation.png) right center no-repeat;
}
```

2- You add this line  (on gPlacesAutocomplete directive) :
```
function getGeolocation() {
    element[0].classList.add('input-geolocation'); // Add this line
    ...
}
```

If you want to add a option on the input field, you can add this (on gPlacesAutocomplete directive) : 
```
scope : {
    ..,
    geolocation: '=?',
    geolocationIcon: '=?'
}
```
and this : 
```
function getGeolocation() {
    // Add a bg icon on the input field
    if($scope.geolocationIcon)
        element[0].classList.add('input-geolocation');
    ...
}
```

**Comment by simonferndriger** [comment]
Thank you very much. However, since I'm new to Angular, I'm not sure if that is what I'm looking for.

I have http://dev.sonnige-aussichten.ch/ - and nearby the input field I placed an `<md-button>` which has the Material click effect. 

What I do so far to "run" this plugin, is the following:

`$scope.autocompleteOptions = {
	componentRestrictions: { country: 'ch' }
 };`

Do I need to change the JavaScript code in "autocomplete.js" for this button to work? Or can I just pass for example a button ID or CSS class name with the options?

**Comment by fcailliez** [comment]
You must create a function for it (on your controller or on  factory).
This function will call a geolocation function that'll do +/- the same thing as mine.

**Comment by simonferndriger** [comment]
OK, so I declare `<md-button ng-click="...">` - but what do I put there?

Or in other words, how is your addon meant to be used (in a "plug-n-play" way)?

**Comment by fcailliez** [comment]
You must create a function for it, on your controller :  
ctrl : 
```
this.getGeolocation = function() {
// This function will do +/- the same thing as mine.
}
```
view : 
`<md-button ng-click="ctrl.getGeolocation()">`

**Comment by simonferndriger** [comment]
OK, good, I can use this. So, if I put everything together, I get this in my controller (which is not yet right, is it)?

`				$scope.getGeolocation = function(){
					 element[0].classList.add('input-geolocation');	
				};
`

**Comment by fcailliez** [comment]
Yes, you can delete this line.

**Comment by simonferndriger** [comment]
I'm not sure if your answer was meant for me? If so, I'm not sure I understand what you mean.

**Pull request closed without merging**
