### PR TITLE
Fixes #13 #19 - Fix logic for forceSelection

### LINKED ISSUE #13: Issue with enabling force-selection clearing input
When I enable force-selection on an input in a bootstrap modal, clicking outside of the autocomplete container autoselects an address for the user, which works fine. However, when I select an address, the input is populated with the information and I still have focus on the input. Losing focus of the input clears it, which is problematic.

For those trying to reproduce this bug, I'm on the most recent version. Here's my code:

HTML

    <form class="form-horizontal" name="propertyForm" ng-submit="propertyForm.$valid && submitProperty()">
      <div class="modal-body">
        <div class="form-group" ng-class="{ 'has-error': propertyForm.address.$invalid && propertyForm.address.$dirty }">
          <label class="control-label col-md-3">
            Address
          </label>
          <div class="col-md-9">
            <input type="text" name="address" class="form-control" placeholder="1234 W 9th St" ng-model="address" g-places-autocomplete force-selection="true" options="options" required>
          </div>
        </div>
  </div>
</form>

My options object

    $scope.options = {
      componentRestrictions: { country: 'us' },
      types: ['geocode']
    };

I have an event listener on the `g-places-autocomplete:select` event as well and it correctly fires.

### PR DESCRIPTION
**Pull request by jasonaden**
Add logic to blur event with forceSelection so it doesn't clear the input

### CODE REVIEW

**Comment by kuhnza** [comment]
Thanks @jasonaden I'm not getting much time to maintain this right now so I've made you a contributor.

**Comment by JetFault** [comment]
Worked for me +1

**Comment by kijanawoodard** [comment]
This appears to fix our issues. Currently using the fork as a bower dependency:

"dependencies": {
   "angular-google-places-autocomplete": "Medycation/angular-google-places-autocomplete#7c5ad7a2905b795ca9409a0c53ba3d1a4eabd6ff"
}

**Comment by mliu95** [comment]
+1 Worked for me

**Comment by jasonaden** [comment]
@kijanawoodard & @mliu95 You should be able to point back to the main repo now. I fixed the merge conflicts and pushed a release.

**Pull request merged**
